## Extraction, Transformation and Loading of the Data

In [1]:
# Import dependencies
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

In [2]:
# Read the data into a Pandas DataFrame
pnw_earthquake_df = pd.read_csv('Resources/query.csv')
pnw_earthquake_df

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2025-05-20T09:29:32.099Z,41.911500,-119.579000,12.800,2.70,ml,6.0,130.95,0.3520,0.1093,...,2025-05-20T16:03:20.912Z,"47 km E of Fort Bidwell, California",earthquake,NaN,4.00,0.390,6.0,reviewed,nn,nn
1,2025-05-19T03:03:05.700Z,40.371334,-125.101166,0.330,2.74,md,22.0,271.00,0.5858,0.3200,...,2025-05-19T03:37:17.828Z,"69 km WNW of Petrolia, CA",earthquake,4.900,13.38,0.110,15.0,automatic,nc,nc
2,2025-05-17T05:51:18.640Z,40.274167,-124.626500,5.630,3.50,mw,83.0,245.00,0.2177,0.2300,...,2025-05-17T22:32:16.201Z,"30 km W of Petrolia, CA",earthquake,0.460,0.68,NaN,6.0,reviewed,nc,nc
3,2025-05-17T05:21:49.130Z,40.300335,-124.510498,5.880,2.93,md,24.0,273.00,0.1290,0.3000,...,2025-05-17T07:47:19.368Z,"19 km W of Petrolia, CA",earthquake,4.390,1.75,0.080,26.0,automatic,nc,nc
4,2025-05-17T05:06:00.660Z,40.294167,-124.574165,8.360,2.95,ml,26.0,278.00,0.1772,0.1500,...,2025-05-17T07:07:19.086Z,"25 km W of Petrolia, CA",earthquake,2.570,1.30,0.152,4.0,automatic,nc,nc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18473,1970-08-08T22:36:40.160Z,47.374833,-123.106500,35.987,2.90,md,5.0,185.00,0.2770,0.1700,...,2016-07-24T23:40:50.770Z,"2 km N of Union, Washington",earthquake,1.580,2.66,0.060,4.0,reviewed,uw,uw
18474,1970-07-29T20:42:31.210Z,48.204333,-119.492667,20.257,2.70,md,11.0,324.00,1.0300,0.3600,...,2016-07-24T23:40:46.170Z,"18 km ESE of Malott, Washington",earthquake,5.208,6.15,0.250,0.0,reviewed,uw,uw
18475,1970-07-11T10:24:30.860Z,48.203500,-121.355333,0.042,3.00,md,4.0,296.00,0.8851,0.1000,...,2016-07-24T23:40:39.570Z,"19 km ESE of Darrington, Washington",earthquake,0.113,0.13,0.070,4.0,reviewed,uw,uw
18476,1970-05-06T17:15:38.030Z,46.882167,-119.455500,0.918,2.50,md,5.0,148.00,0.1138,0.1900,...,2016-07-24T23:40:31.770Z,"13 km E of Royal City, Washington",earthquake,1.377,2.80,0.240,0.0,reviewed,uw,uw
18477,1970-01-01T06:44:28.060Z,46.332833,-118.391167,-0.260,2.60,md,6.0,299.00,0.4814,0.1500,...,2016-07-24T23:40:13.680Z,"6 km WNW of Prescott, Washington",earthquake,0.144,0.09,0.210,0.0,reviewed,uw,uw

In [3]:
# Inspect columns 
pnw_earthquake_df.columns

Index(['time', 'latitude', 'longitude', 'depth', 'mag', 'magType', 'nst',
       'gap', 'dmin', 'rms', 'net', 'id', 'updated', 'place', 'type',
       'horizontalError', 'depthError', 'magError', 'magNst', 'status',
       'locationSource', 'magSource'],
      dtype='object')

In [4]:
# Summary of the pnw_earthquake_data_final.csv
pnw_earthquake_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18478 entries, 0 to 18477
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   time             18478 non-null  object
 1   latitude         18478 non-null  float64
 2   longitude        18478 non-null  float64
 3   depth            18476 non-null  float64
 4   mag              18478 non-null  float64
 5   magType          18476 non-null  object
 6   nst              18028 non-null  float64
 7   gap              18082 non-null  float64
 8   dmin             16308 non-null  float64
 9   rms              18174 non-null  float64
 10  net              18478 non-null  object
 11  id               18478 non-null  object
 12  updated          18478 non-null  object
 13  place            18478 non-null  object
 14  type             18478 non-null  object
 15  horizontalError  16492 non-null  float64
 16  depthError       17862 non-null  float64
 17  magError         15205 non-null  float64
 18  magNst           17871 non-null  float64
 19  status           18478 non-null  object
 20  locationSource   18478 non-null  object
 21  magSource        18478 non-null  object
dtypes: float64(12), object(10)
memory usage: 3.1+ MB

In [5]:
# Convert 'time' to datetime
pnw_earthquake_df['time'] = pd.to_datetime(pnw_earthquake_df['time'])

In [6]:
# Check if the coversion happened
pnw_earthquake_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18478 entries, 0 to 18477
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   time             18478 non-null  datetime64[ns, UTC]
 1   latitude         18478 non-null  float64
 2   longitude        18478 non-null  float64
 3   depth            18476 non-null  float64
 4   mag              18478 non-null  float64
 5   magType          18476 non-null  object
 6   nst              18028 non-null  float64
 7   gap              18082 non-null  float64
 8   dmin             16308 non-null  float64
 9   rms              18174 non-null  float64
 10  net              18478 non-null  object
 11  id               18478 non-null  object
 12  updated          18478 non-null  object
 13  place            18478 non-null  object
 14  type             18478 non-null  object
 15  horizontalError  16492 non-null  float64
 16  depthError       17862 non-null  float64
 17  magError         15205 non-null  float64
 18  magNst           17871 non-null  float64
 19  status           18478 non-null  object
 20  locationSource   18478 non-null  object
 21  magSource        18478 non-null  object
dtypes: datetime64[ns, UTC](1), float64(12), object(9)
memory usage: 3.1+ MB

In [8]:
# Feature Engineering: extract year, month, day, hour
pnw_earthquake_df['year'] = pnw_earthquake_df['time'].dt.year
pnw_earthquake_df['month'] = pnw_earthquake_df['time'].dt.month
pnw_earthquake_df['day'] = pnw_earthquake_df['time'].dt.day
pnw_earthquake_df['hour'] = pnw_earthquake_df['time'].dt.hour

In [9]:
# Check if the extraction was completed
pnw_earthquake_df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,depthError,magError,magNst,status,locationSource,magSource,year,month,day,hour
0,2025-05-20 09:29:32.099000+00:00,41.911500,-119.579000,12.80,2.70,ml,6.0,130.95,0.3520,0.1093,...,4.00,0.390,6.0,reviewed,nn,nn,2025,5,20,9
1,2025-05-19 03:03:05.700000+00:00,40.371334,-125.101166,0.33,2.74,md,22.0,271.00,0.5858,0.3200,...,13.38,0.110,15.0,automatic,nc,nc,2025,5,19,3
2,2025-05-17 05:51:18.640000+00:00,40.274167,-124.626500,5.63,3.50,mw,83.0,245.00,0.2177,0.2300,...,0.68,NaN,6.0,reviewed,nc,nc,2025,5,17,5
3,2025-05-17 05:21:49.130000+00:00,40.300335,-124.510498,5.88,2.93,md,24.0,273.00,0.1290,0.3000,...,1.75,0.080,26.0,automatic,nc,nc,2025,5,17,5
4,2025-05-17 05:06:00.660000+00:00,40.294167,-124.574165,8.36,2.95,ml,26.0,278.00,0.1772,0.1500,...,1.30,0.152,4.0,automatic,nc,nc,2025,5,17,5

In [12]:
# Inspect and identify nulls
null_summary = pnw_earthquake_df.isnull().sum()
null_columns = null_summary[null_summary > 0].index.tolist()
null_summary

time                  0
latitude              0
longitude             0
depth                 2
mag                   0
magType               2
nst                 450
gap                 396
dmin               2170
rms                 304
net                   0
id                    0
updated               0
place                 0
type                  0
horizontalError    1986
depthError          616
magError           3273
magNst              607
status                0
locationSource        0
magSource             0
year                  0
month                 0
day                   0
hour                  0
dtype: int64

In [14]:
# Drop columns with >30% missing values
drop_cols = [col for col in null_columns if pnw_earthquake_df[col].isnull().mean() > 0.3]
pnw_df_cleaned = pnw_earthquake_df.drop(columns=drop_cols)
pnw_earthquake_df

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,depthError,magError,magNst,status,locationSource,magSource,year,month,day,hour
0,2025-05-20 09:29:32.099000+00:00,41.911500,-119.579000,12.800,2.70,ml,6.0,130.95,0.3520,0.1093,...,4.00,0.390,6.0,reviewed,nn,nn,2025,5,20,9
1,2025-05-19 03:03:05.700000+00:00,40.371334,-125.101166,0.330,2.74,md,22.0,271.00,0.5858,0.3200,...,13.38,0.110,15.0,automatic,nc,nc,2025,5,19,3
2,2025-05-17 05:51:18.640000+00:00,40.274167,-124.626500,5.630,3.50,mw,83.0,245.00,0.2177,0.2300,...,0.68,NaN,6.0,reviewed,nc,nc,2025,5,17,5
3,2025-05-17 05:21:49.130000+00:00,40.300335,-124.510498,5.880,2.93,md,24.0,273.00,0.1290,0.3000,...,1.75,0.080,26.0,automatic,nc,nc,2025,5,17,5
4,2025-05-17 05:06:00.660000+00:00,40.294167,-124.574165,8.360,2.95,ml,26.0,278.00,0.1772,0.1500,...,1.30,0.152,4.0,automatic,nc,nc,2025,5,17,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18473,1970-08-08 22:36:40.160000+00:00,47.374833,-123.106500,35.987,2.90,md,5.0,185.00,0.2770,0.1700,...,2.66,0.060,4.0,reviewed,uw,uw,1970,8,8,22
18474,1970-07-29 20:42:31.210000+00:00,48.204333,-119.492667,20.257,2.70,md,11.0,324.00,1.0300,0.3600,...,6.15,0.250,0.0,reviewed,uw,uw,1970,7,29,20
18475,1970-07-11 10:24:30.860000+00:00,48.203500,-121.355333,0.042,3.00,md,4.0,296.00,0.8851,0.1000,...,0.13,0.070,4.0,reviewed,uw,uw,1970,7,11,10
18476,1970-05-06 17:15:38.030000+00:00,46.882167,-119.455500,0.918,2.50,md,5.0,148.00,0.1138,0.1900,...,2.80,0.240,0.0,reviewed,uw,uw,1970,5,6,17
18477,1970-01-01 06:44:28.060000+00:00,46.332833,-118.391167,-0.260,2.60,md,6.0,299.00,0.4814,0.1500,...,0.09,0.210,0.0,reviewed,uw,uw,1970,1,1,6

This attempt did not work since there were no columns with more than 30% of the values are nulls. Since we will be using the final output for ML, we decided to place imputed values in the fields where values were missing.

In [15]:
# Impute numeric columns with median
impute_cols = [col for col in null_columns if col not in drop_cols and pnw_earthquake_df[col].dtype in ['float64', 'int64']]
for col in impute_cols:
    pnw_df_cleaned[col] = pnw_df_cleaned[col].fillna(pnw_df_cleaned[col].median())

In [16]:
# Impute categorical columns with 'Unknown'
impute_obj_cols = [col for col in null_columns if col not in drop_cols and pnw_earthquake_df[col].dtype == 'object']
for col in impute_obj_cols:
    pnw_df_cleaned[col] = pnw_df_cleaned[col].fillna("Unknown")

In [17]:
# View the cleaned DataFrame
pnw_df_cleaned

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,depthError,magError,magNst,status,locationSource,magSource,year,month,day,hour
0,2025-05-20 09:29:32.099000+00:00,41.911500,-119.579000,12.800,2.70,ml,6.0,130.95,0.3520,0.1093,...,4.00,0.390,6.0,reviewed,nn,nn,2025,5,20,9
1,2025-05-19 03:03:05.700000+00:00,40.371334,-125.101166,0.330,2.74,md,22.0,271.00,0.5858,0.3200,...,13.38,0.110,15.0,automatic,nc,nc,2025,5,19,3
2,2025-05-17 05:51:18.640000+00:00,40.274167,-124.626500,5.630,3.50,mw,83.0,245.00,0.2177,0.2300,...,0.68,0.120,6.0,reviewed,nc,nc,2025,5,17,5
3,2025-05-17 05:21:49.130000+00:00,40.300335,-124.510498,5.880,2.93,md,24.0,273.00,0.1290,0.3000,...,1.75,0.080,26.0,automatic,nc,nc,2025,5,17,5
4,2025-05-17 05:06:00.660000+00:00,40.294167,-124.574165,8.360,2.95,ml,26.0,278.00,0.1772,0.1500,...,1.30,0.152,4.0,automatic,nc,nc,2025,5,17,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18473,1970-08-08 22:36:40.160000+00:00,47.374833,-123.106500,35.987,2.90,md,5.0,185.00,0.2770,0.1700,...,2.66,0.060,4.0,reviewed,uw,uw,1970,8,8,22
18474,1970-07-29 20:42:31.210000+00:00,48.204333,-119.492667,20.257,2.70,md,11.0,324.00,1.0300,0.3600,...,6.15,0.250,0.0,reviewed,uw,uw,1970,7,29,20
18475,1970-07-11 10:24:30.860000+00:00,48.203500,-121.355333,0.042,3.00,md,4.0,296.00,0.8851,0.1000,...,0.13,0.070,4.0,reviewed,uw,uw,1970,7,11,10
18476,1970-05-06 17:15:38.030000+00:00,46.882167,-119.455500,0.918,2.50,md,5.0,148.00,0.1138,0.1900,...,2.80,0.240,0.0,reviewed,uw,uw,1970,5,6,17
18477,1970-01-01 06:44:28.060000+00:00,46.332833,-118.391167,-0.260,2.60,md,6.0,299.00,0.4814,0.1500,...,0.09,0.210,0.0,reviewed,uw,uw,1970,1,1,6

In [18]:
# Check if there are anymore nulls
pnw_df_cleaned.isnull().sum()

time               0
latitude           0
longitude          0
depth              0
mag                0
magType            0
nst                0
gap                0
dmin               0
rms                0
net                0
id                 0
updated            0
place              0
type               0
horizontalError    0
depthError         0
magError           0
magNst             0
status             0
locationSource     0
magSource          0
year               0
month              0
day                0
hour               0
dtype: int64

In [19]:
# Export the DataFrame as a CSV file. 
pnw_df_cleaned.to_csv("Resources/pnw_final.csv", encoding='utf8', index=False)